import * as themes from '@uiw/codemirror-themes-all';

export const editorLightThemes = [
  { label: 'GitHub Light', value: 'github-light', theme: themes.githubLight },
  { label: 'Basic Light', value: 'basic-light', theme: themes.basicLight },
  { label: 'Console Light', value: 'console-light', theme: themes.consoleLight },
  { label: 'Duotone Light', value: 'duotone-light', theme: themes.duotoneLight },
  { label: 'Eclipse', value: 'eclipse', theme: themes.eclipse },
  { label: 'Material Light', value: 'material-light', theme: themes.materialLight },
  { label: 'Noctis Lilac', value: 'noctis-lilac', theme: themes.noctisLilac },
  { label: 'Quiet Light', value: 'quietlight', theme: themes.quietlight },
  { label: 'Solarized Light', value: 'solarized-light', theme: themes.solarizedLight },
  { label: 'Tokyo Night Day', value: 'tokyo-night-day', theme: themes.tokyoNightDay },
  { label: 'VS Code Light', value: 'vscode-light', theme: themes.vscodeLightInit() },
  { label: 'White Light', value: 'white-light', theme: themes.whiteLight },
  { label: 'XCode Light', value: 'xcode-light', theme: themes.xcodeLight },
];

export const editorDarkThemes = [
  { label: 'GitHub Dark', value: 'github-dark', theme: themes.githubDark },
  { label: 'abcdef', value: 'abcdef', theme: themes.abcdef },
  { label: 'Abyss', value: 'abyss', theme: themes.abyss },
  { label: 'Android Studio', value: 'androidstudio', theme: themes.androidstudio },
  { label: 'Andromeda', value: 'andromeda', theme: themes.andromeda },
  { label: 'Aura', value: 'aura', theme: themes.aura },
  { label: 'Basic Dark', value: 'basic-dark', theme: themes.basicDark },
  { label: 'Bespin', value: 'bespin', theme: themes.bespin },
  { label: 'Console Dark', value: 'console-dark', theme: themes.consoleDark },
  { label: 'Copilot', value: 'copilot', theme: themes.copilot },
  { label: 'Darcula', value: 'darcula', theme: themes.darcula },
  { label: 'Dracula', value: 'dracula', theme: themes.dracula },
  { label: 'Duotone Dark', value: 'duotone-dark', theme: themes.duotoneDark },
  { label: 'Gruvbox Dark', value: 'gruvbox-dark', theme: themes.gruvboxDark },
  { label: 'Kimbie Dark', value: 'kimbie-dark', theme: themes.kimbie },
  { label: 'Material Dark', value: 'material-dark', theme: themes.materialDark },
  { label: 'Monokai', value: 'monokai', theme: themes.monokai },
  { label: 'Monokai Dimmed', value: 'monokai-dimmed', theme: themes.monokaiDimmed },
  { label: 'Nord', value: 'nord', theme: themes.nord },
  { label: 'Okaidia', value: 'okaidia', theme: themes.okaidia },
  { label: 'Red', value: 'red', theme: themes.red },
  { label: 'Solarized Dark', value: 'solarized-dark', theme: themes.solarizedDark },
  { label: 'Sublime', value: 'sublime', theme: themes.sublime },
  { label: 'Tokyo Night', value: 'tokyo-night', theme: themes.tokyoNight },
  { label: 'Tokyo Night Storm', value: 'tokyo-night-storm', theme: themes.tokyoNightStorm },
  { label: 'Tomorrow Night Blue', value: 'tomorrow-night-blue', theme: themes.tomorrowNightBlue },
  { label: 'VS Code Dark', value: 'vscode-dark', theme: themes.vscodeDarkInit() },
  { label: 'White Dark', value: 'white-dark', theme: themes.whiteDark },
  { label: 'XCode Dark', value: 'xcode-dark', theme: themes.xcodeDark },
];
