name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Setup Bun
      run: npm install -g bun

    - name: Checkout
      uses: actions/checkout@v4

    - name: Fetch geogebra assets
      run: |
        git clone https://github.com/Hans774882968/geogebra-resource.git temp_geogebra
        mkdir -p public/geogebra
        cp -r temp_geogebra/* public/geogebra/
        rm -rf temp_geogebra

    - name: Install dependencies
      run:
        bun install

    - name: Build Project
      run: |
        bun run build
      env:
        # TODO: try to make vars.VITE_DEPLOY_TARGET accessible
        VITE_DEPLOY_TARGET: ${{ vars.VITE_DEPLOY_TARGET || 'github-pages' }}

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        commit_message: "Deploy tpm - ${{ github.event.head_commit.message }}"
